# app/config/routing.yml
applicationBundle:
 resource: "@OpenDeviceLabApplicationBundle/Resources/config/routing.yml"

adminBundle: 
 resource: "@OpenDeviceLabAdminBundle/Resources/config/routing.yml"

genemu_base64:
 resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"
