# app/config/routing.yml
applicationBundle:
 resource: "@OpenDeviceLabApplicationBundle/Resources/config/routing.yml"

adminBundle: 
 resource: "@OpenDeviceLabAdminBundle/Resources/config/routing.yml"
