# app/config/routing.yml
applicationBundle:
 resource: "@OpenDeviceLabApplicationBundle/Resources/config/routing.yml"

#admin: 
# resource: "@OpdenDeviceLabAdminBundle/Controller/DefaultController.php"
# type:     annotation
# prefix:   
