security:
    encoders:
        OpenDeviceLab\ApplicationBundle\Entity\User: 
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin:
            entity: { class: OpenDeviceLabApplicationBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/admin
            anonymous: ~
            form_login:             
                login_path: /login
                check_path: /admin/login_check
                default_target_path: admin_index
                always_use_default_target_path: true
            logout: 
                path: /logout

    access_control:
        - { path: ^/admin.*$, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
