security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin:
            entity: { class: OpenDeviceLabApplicationBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/admin
            form_login:
                check_path: /login_check
                login_path: /login

    access_control:
        - { path: ^/admin.*$, roles: ROLE_SUPER_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
