default:
 resource: "@OpenDeviceLabAdminBundle/Controller/DefaultController.php"
 type: annotation
 prefix: /admin

users:
 resource: "@OpenDeviceLabAdminBundle/Controller/UserController.php"
 type: annotation
 prefix: /admin

device:
 resource: "@OpenDeviceLabAdminBundle/Controller/DeviceController.php"
 type: annotation
 prefix: /admin

security:
 resource: "@OpenDeviceLabAdminBundle/Controller/SecurityController.php"
 type: annotation
 
login_check: 
 pattern: /admin/login_check
